### PR TITLE
Isu0033 upgrade the system to use django version 2.2

### PR DESCRIPTION
**Pull request by DilshadGit**
Please readme file and see the changes when you finished with all code changes after update django==2.2 make sure you delete your current database and delete all migrations except __init__.py run migrations and follow the readme file for test before merge.

### CODE REVIEW

**Comment by tine3700** [comment]
Hi Dilshad.
There is a merge conflict.
Can you fix please?

**Comment by DilshadGit** [comment]
Yes I will handle it I am in the city yet but I will do it when back home.

**Comment by DilshadGit** [comment]
Hi Christine
I have update some packages in requirements.txt .
This branch Isu0033 upgrade the system to use django version 2.2 is working now I will send merge request again.
Thanks

**Comment by nherriot** [comment]
Dilshad,  please revert this Pull request. It has not been reviewed!!!

**Comment by DilshadGit** [comment]
Hi Nick

In this branch I have not changed anything except  the upgraded version of
django1.9 to django2.2.27 in requierments.txt file.

In this line in settings.py DEVELOPER_MACHINES = ['Zenbook-UX32A',
'kieran', 'dilux', 'my-linux-machine', '*']
I removed my virtualbox machine name changed to dilux.
In the settings.py where if socket.gethostname() add not to use sqlite3
make it easy to use the database without username and pass.

Before >> if socket.gethostname() in DEVELOPER_MACHINES:

Now >> if socket.gethostname() not in DEVELOPER_MACHINES:

You can test it and it works fine with both ways. I just added not to not
create extra db with postgresql.

asgiref==3.5.2 >> upgraded to the new version which automatically installed
this >> backports.zoneinfo==0.2.1 is included when you upgrade.

When the django upgrade to 2.2.27 and you use postgresql you need to
install psycopg2-binary==2.9.3

I may upgrade another two packages (django-markdown-deux==1.0.5,
django-pagedown==2.2.1) , nothing else.

Compare your master branch with one of the other branches; there are not
many changes at all.

Let me know if you have any questions.

Thanks

Dilshad
.

*Dilshad Abdulla*
Flat 4
16 Glebe Road
Chelmsford
CM1 1QG

Mobile: +44(0)7825 810 648
Portfolio: https://www.dilshadabdulla.net
<http://uk.linkedin.com/in/dilshadabdulla/>

https://www.linkedin.com/in/dilshadabdulla/
https://github.com/DilshadGit
http://stackoverflow.com/users/2700672/dilmac

**Pull request merged**
