### PR TITLE
45 remove all models that are not used on the system

### PR DESCRIPTION
**Pull request by DilshadGit**
To test this:

1. Go to branch: 45-remove-all-models-that-are-not-used-on-the-system
2. Git pull.
3. Run server in **dev** mode.
  ```
     /> cd app/
     /> export ENVIRONMENT=dev
     /> python manage.py runserver 8005
4. Make sure the directories xxx are missing.
5. 

- Delete all models of accounts, catalog and qrecode all those codes are not Django vanilla.
- Removed all migrations and run migrate to make sure all is working and one single migration.
- Removed admin of those app models are delete.
-  Django admin working OK.
- Blog Add, list and detail are working on admin and when the user is logged in if use the buttons. 
- Update blogs has bug and fixed as well.

I am just wondering if the same models of above are required as Django vanilla (Django rest framework)?

### CODE REVIEW

**Review by DilshadGit — COMMENTED** [review]
Please check the models has been removed

**Review by DilshadGit — COMMENTED** [review]
The new update between MIDDLEWARE_CLASSES in django==1.11 and MIDDLEWARE in django==2

**Review by DilshadGit — COMMENTED** [review]
is just duplicated sorry about it.

**Review by DilshadGit — COMMENTED** [review]
removed all admin codes connected to the models and admin site working login and logout OK

**Review by DilshadGit — COMMENTED** [review]
Blog apps working fine only update_post need some changed:
blogs/templates/update.html
```<form action="" method="POST" accept-charset="utf-8">```
Because the form update is include media need to add following:
```<form action="" method="POST" accept-charset="utf-8" enctype="multipart/form-data">```

blogs/views.py
The ```form = PostForm(request.POST, request.FILES, instance=blog_post)``` was identified after the post because we update the form object before if statement. For adding new post need create after ```if request.method == 'POST'``` , but if we want to update the post already created and save in the database we have to create the form object before the ```if request.method == 'POST'``` because use as GET and POST changed to:
```form = PostForm(request.POST or None, request.FILES or None, instance=blog_post)```
(or None) has added to update the request or nothing the same for the request.FILES.

We don't need form object and context after else has to return only message if there is an error.

 ```
context = {'form': form}
 return render(request, template_name, context)
```
Last change removed form object:
```form = PostForm(instance=blog_post)```

The context here is static not updated need also to change to instance object.
```
context = {
        'main_title': 'Blogs At Noisy Atom',
        'description1': 'Read all about the latest thought, what we are working on and how we are progressing! A brain dump of where we are at!',
        'description2': 'We hope you enjoy our thoughts...',
        'description3': '',
        'form': form}
```

Changed to:
```
context = {
        'main_title': blog_post.title,
        'blog_post': blog_post,
        'form': form
    }
```

**Review by DilshadGit — COMMENTED** [review]
Here in the forms.py you can use:
fields = '__all__'
or you can leave it like before

**Comment by nherriot** [comment]
What pull request does this relate too?
How should i test it if it's not obvious?
The pull request should be rejected due to it's poor description. But I shall try my best to review it.

**Review by nherriot — CHANGES_REQUESTED** [review]
The issue has a change to state the removal of all unused applications.
Just to be CRYSTAL CLEAR.
Remove ALL unused applications from the system that are not part of Django 2.0 except for BLOGS.

**Comment by DilshadGit** [comment]
@nherriot Could you please check the code review as requested. Thanks

**Review by nherriot — APPROVED** [review]
LGTM

**Pull request merged**
