### PR TITLE
Us005 change menu items to only show menus that work for noisy atom

### PR DESCRIPTION
**Pull request by nherriot**
Added a test case.
Added a coming soon page.
Routed all the project menus to our coming soon page.
Removed or commented out our unused menus.

### CODE REVIEW

**Comment by nherriot** [comment]
[US005_Update_menu_bar](https://trello.com/c/KmZH54tM/33-us005updatemenubar)

**Comment by DilshadGit** [comment]
[US005_Update_menu_bar](https://trello.com/c/KmZH54tM/33-us005updatemenubar)

**Comment by DilshadGit** [comment]
[US005_Update_menu_bar](https://trello.com/c/KmZH54tM/33-us005updatemenubar)

**Comment by DilshadGit** [comment]
[US005_Update_menu_bar](https://trello.com/c/KmZH54tM/33-us005updatemenubar)

**Pull request merged**
